"""First

Revision ID: ec79fc0824e1
Revises: b3fddb02cdec
Create Date: 2022-10-06 04:33:50.384669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec79fc0824e1'
down_revision = 'b3fddb02cdec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
